UI_TEXTS = {
    "en": {
        "welcome": "Hello! 👋\n\nWelcome to Swedish Practice Bot 🇸🇪\n\nChoose language:",
        "choose_topic": "Now choose a topic:",
        "lang_selected": "Language selected ✅",
        "topic_selected": "Topic selected: {theme} ✅",
        "topic_label": "Topic",
        "question": 'What does "{word}" mean?',
        "correct": "Correct ✔\n\n{word} = {answer}",
        "wrong": "Wrong ❌\n\nCorrect answer: {word} = {answer}",
        "next_word": "Next word",
        "main_menu": "Main menu",
        "reinforce_words": "Practice words",
        "help": "Available commands:\n/start - open main menu\n/word - start word practice\n/help - show help",
        "choose_lang_first": "First choose language.",
        "choose_topic_first": "Now choose a topic.",
        "settings_missing": "Session settings not found. Please start again with /start.",
        "stats": "You answered correctly: {correct} out of {total} 👍",
        "choose_language_again": "Please choose a new language",
        "choose_mode": "Choose training mode:",
        "mode_words": "🧠 Guess the word",
        "mode_nouns": "📚 Noun forms",
        "mode_verbs": "⚡ Verb forms",
        "noun_question": 'Choose the form: {form}\n"{translation} / {word}"',
        "noun_correct": "Correct ✔\n\n{word} = {answer}",
        "noun_wrong": "Wrong ❌\n\nCorrect answer: {word} = {answer}",
        "choose_verb_group": "Choose verb group:",
        "verb_group_1": "Group 1",
        "verb_group_2": "Group 2",
        "verb_group_3": "Group 3",
        "verb_group_4": "Group 4",
        "verb_group_all": "All verbs",
        "verb_correct": "Correct ✔\n\n{word} = {answer}",
        "verb_wrong": "Wrong ❌\n\nCorrect answer: {word} = {answer}",

    },
    "ru": {
        "welcome": "Привет! 👋\n\nДобро пожаловать в Swedish Practice Bot 🇸🇪\n\nВыберите язык:",
        "choose_topic": "Теперь выберите тему:",
        "lang_selected": "Язык выбран ✅",
        "topic_selected": "Тема выбрана: {theme} ✅",
        "topic_label": "Тема",
        "question": 'Что обозначает слово "{word}"?',
        "correct": "Правильно ✔\n\n{word} = {answer}",
        "wrong": "Неправильно ❌\n\nПравильный ответ: {word} = {answer}",
        "next_word": "Следующее слово",
        "main_menu": "Главное меню",
        "reinforce_words": "Закрепить слова",
        "help": "Доступные команды:\n/start - открыть меню\n/word - начать тренировку слов\n/help - помощь",
        "choose_lang_first": "Сначала выберите язык.",
        "choose_topic_first": "Теперь выберите тему.",
        "settings_missing": "Настройки сессии не найдены. Пожалуйста, начните заново через /start.",
        "stats": "Вы ответили правильно на {correct} из {total} 👍",
        "choose_language_again": "Пожалуйста, выберите новый язык",
        "choose_mode": "Выберите режим тренировки:",
        "mode_words": "🧠 Угадай слово",
        "mode_nouns": "📚 Формы существительных",
        "mode_verbs": "⚡ Формы глаголов",
        "noun_question": 'Выберите форму слова: {form}\n"{translation} / {word}"',
        "noun_correct": "Правильно ✔\n\n{word} = {answer}",
        "noun_wrong": "Неправильно ❌\n\nПравильный ответ: {word} = {answer}",
        "choose_verb_group": "Выберите группу глаголов:",
        "verb_group_1": "Группа 1",
        "verb_group_2": "Группа 2",
        "verb_group_3": "Группа 3",
        "verb_group_4": "Группа 4",
        "verb_group_all": "Все глаголы",
        "verb_correct": "Правильно ✔\n\n{word} = {answer}",
        "verb_wrong": "Неправильно ❌\n\nПравильный ответ: {word} = {answer}",

    },
    "uk": {
        "welcome": "Привіт! 👋\n\nЛаскаво просимо до Swedish Practice Bot 🇸🇪\n\nОберіть мову:",
        "choose_topic": "Тепер оберіть тему:",
        "lang_selected": "Мову обрано ✅",
        "topic_selected": "Тему обрано: {theme} ✅",
        "topic_label": "Тема",
        "question": 'Що означає слово "{word}"?',
        "correct": "Правильно ✔\n\n{word} = {answer}",
        "wrong": "Неправильно ❌\n\nПравильна відповідь: {word} = {answer}",
        "next_word": "Наступне слово",
        "main_menu": "Головне меню",
        "reinforce_words": "Закріпити слова",
        "help": "Доступні команди:\n/start - відкрити меню\n/word - почати тренування слів\n/help - допомога",
        "choose_lang_first": "Спочатку оберіть мову.",
        "choose_topic_first": "Тепер оберіть тему.",
        "settings_missing": "Налаштування сесії не знайдено. Будь ласка, почніть знову через /start.",
        "stats": "Ви відповіли правильно на {correct} з {total} 👍",
        "choose_language_again": "Будь ласка, оберіть нову мову",
        "choose_mode": "Оберіть режим тренування:",
        "mode_words": "🧠 Вгадай слово",
        "mode_nouns": "📚 Форми іменників",
        "mode_verbs": "⚡ Форми дієслів",
        "noun_question": 'Оберіть форму: {form}\n"{translation} / {word}"',
        "noun_correct": "Правильно ✔\n\n{word} = {answer}",
        "noun_wrong": "Неправильно ❌\n\nПравильна відповідь: {word} = {answer}",
        "choose_verb_group": "Оберіть групу дієслів:",
        "verb_group_1": "Група 1",
        "verb_group_2": "Група 2",
        "verb_group_3": "Група 3",
        "verb_group_4": "Група 4",
        "verb_group_all": "Усі дієслова",
        "verb_correct": "Правильно ✔\n\n{word} = {answer}",
        "verb_wrong": "Неправильно ❌\n\nПравильна відповідь: {word} = {answer}",

    }
}
