WORD_QUIZ_DATA = {
    "Ett jobberbjudande": {
        "ett erbjudande": {"en": "offer", "ru": "предложение", "uk": "пропозиція"},
        "en ekonom": {"en": "economist", "ru": "экономист", "uk": "економіст"},
        "en möbel": {"en": "piece of furniture", "ru": "предмет мебели", "uk": "предмет меблів"},
        "ett företag": {"en": "company", "ru": "company", "uk": "компанія"},
        "en utbildning": {"en": "education", "ru": "образование", "uk": "освіта"},
        "ett yrke": {"en": "profession", "ru": "профессия", "uk": "професія"},
        "ett val": {"en": "choice", "ru": "выбор", "uk": "вибір"},
        "nuvarande": {"en": "current", "ru": "нынешний", "uk": "поточний"},
        "ett personalrum": {"en": "staff room", "ru": "комната персонала", "uk": "кімната персоналу"},
        "en kollega": {"en": "colleague", "ru": "коллега", "uk": "колега"},
        "nyfiken": {"en": "curious", "ru": "любопытный", "uk": "цікавий"},
        "generad": {"en": "embarrassed", "ru": "смущённый", "uk": "зніяковілий"},
        "klagar": {"en": "complains", "ru": "жалуется", "uk": "скаржиться"},
        "en träningsvärk": {"en": "muscle soreness", "ru": "крепатура", "uk": "крепатура"},
        "en fikarast": {"en": "coffee break", "ru": "кофейный перерыв", "uk": "кава-пауза"},
        "en tjänst": {"en": "position", "ru": "должность", "uk": "посада"},
        "ett huvudkontor": {"en": "head office", "ru": "главный офис", "uk": "головний офіс"},
        "en projektledare": {"en": "project manager", "ru": "руководитель проекта", "uk": "керівник проєкту"},
        "en arbetsuppgift": {"en": "task", "ru": "рабочая задача", "uk": "робоче завдання"},
        "går upp": {"en": "gets up", "ru": "встаёт", "uk": "встає"},
        "smickrad": {"en": "flattered", "ru": "польщённый", "uk": "задоволений лестощами"},
        "lockande": {"en": "tempting", "ru": "заманчивый", "uk": "привабливий"},
        "kluven": {"en": "torn", "ru": "сомневающийся", "uk": "вагається"},
        "ett ansvar": {"en": "responsibility", "ru": "ответственность", "uk": "відповідальність"},
        "en utmaning": {"en": "challenge", "ru": "вызов", "uk": "виклик"},
        "utvecklar": {"en": "develops", "ru": "развивает", "uk": "розвиває"},
        "en roll": {"en": "role", "ru": "роль", "uk": "роль"},
        "en yrkesroll": {"en": "professional role", "ru": "профессиональная роль", "uk": "професійна роль"},
        "en arbetsplats": {"en": "workplace", "ru": "рабочее место", "uk": "робоче місце"},
        "klarar av": {"en": "manages", "ru": "справляется", "uk": "справляється"},
        "en resväg": {"en": "commute", "ru": "дорога до работы", "uk": "дорога до роботи"},
        "en enkel väg": {"en": "one way", "ru": "дорога в одну сторону", "uk": "дорога в один бік"},
        "överfull": {"en": "overcrowded", "ru": "переполненный", "uk": "переповнений"},
        "en rusningstid": {"en": "rush hour", "ru": "час пик", "uk": "година пік"},
        "i värsta fall": {"en": "in the worst case", "ru": "в худшем случае", "uk": "у гіршому випадку"},
        "beklagar sig": {"en": "complains", "ru": "жалуется", "uk": "скаржиться"},
        "motion": {"en": "exercise", "ru": "физическая активность", "uk": "фізична активність"},
        "rör på sig": {"en": "moves", "ru": "двигается", "uk": "рухається"},
        "en plånbok": {"en": "wallet", "ru": "кошелёк", "uk": "гаманець"},
        "samtidigt": {"en": "at the same time", "ru": "одновременно", "uk": "одночасно"},
        "före detta": {"en": "former", "ru": "бывший", "uk": "колишній"},
        "gör slut": {"en": "breaks up", "ru": "расстаётся", "uk": "розлучається"},
        "förkrossad": {"en": "heartbroken", "ru": "убит горем", "uk": "розбитий горем"},
        "tröstar": {"en": "comforts", "ru": "утешает", "uk": "втішає"},
        "snurrar": {"en": "spins", "ru": "кружится", "uk": "крутиться"},
    },

    "Ett svårt val": {
        "ett val": {"en": "choice", "ru": "выбор", "uk": "вибір"},
        "sträcker på sig": {"en": "stretches", "ru": "потягивается", "uk": "потягується"},
        "en rast": {"en": "break", "ru": "перерыв", "uk": "перерва"},
        "ser fram emot": {"en": "looks forward to", "ru": "ждёт с нетерпением", "uk": "чекає з нетерпінням"},
        "ett drömjobb": {"en": "dream job", "ru": "работа мечты", "uk": "робота мрії"},
        "en bilmekaniker": {"en": "car mechanic", "ru": "автомеханик", "uk": "автомеханік"},
        "ett fordonsprogram": {"en": "vehicle program", "ru": "программа автотехники", "uk": "програма транспорту"},
        "söker": {"en": "applies", "ru": "подаёт заявку", "uk": "подає заявку"},
        "inte ens": {"en": "not even", "ru": "даже не", "uk": "навіть не"},
        "en intervju": {"en": "interview", "ru": "собеседование", "uk": "співбесіда"},
        "hög": {"en": "high", "ru": "высокий", "uk": "високий"},
        "en arbetslöshet": {"en": "unemployment", "ru": "безработица", "uk": "безробіття"},
        "fortfarande": {"en": "still", "ru": "всё ещё", "uk": "досі"},
        "i alla fall": {"en": "anyway", "ru": "в любом случае", "uk": "у будь-якому разі"},
        "ett arbetspass": {"en": "work shift", "ru": "рабочая смена", "uk": "робоча зміна"},
        "dessutom": {"en": "in addition", "ru": "кроме того", "uk": "крім того"},
        "ett ob-tillägg": {"en": "overtime bonus", "ru": "доплата за неудобное время", "uk": "доплата за незручний час"},
        "besviken": {"en": "disappointed", "ru": "разочарованный", "uk": "розчарований"},
        "å andra sidan": {"en": "on the other hand", "ru": "с другой стороны", "uk": "з іншого боку"},
        "en timvikarie": {"en": "hourly substitute", "ru": "временный работник", "uk": "тимчасовий працівник"},
        "en fast tjänst": {"en": "permanent position", "ru": "постоянная должность", "uk": "постійна посада"},
    },

    "Vänner för livet": {
        "ett tåg": {"en": "train", "ru": "поезд", "uk": "поїзд"},
        "stannar": {"en": "stops", "ru": "останавливается", "uk": "зупиняється"},
        "en tågstation": {"en": "train station", "ru": "железнодорожная станция", "uk": "залізнична станція"},
        "Japan": {"en": "Japan", "ru": "Япония", "uk": "Японія"},
        "en hund": {"en": "dog", "ru": "собака", "uk": "собака"},
        "ingen": {"en": "no one", "ru": "никто", "uk": "ніхто"},
        "en ägare": {"en": "owner", "ru": "владелец", "uk": "власник"},
        "ensam": {"en": "alone", "ru": "один", "uk": "сам"},
        "tar med": {"en": "takes with", "ru": "берёт с собой", "uk": "бере з собою"},
        "en vän": {"en": "friend", "ru": "друг", "uk": "друг"},
        "jobbar": {"en": "works", "ru": "работает", "uk": "працює"},
        "ett universitet": {"en": "university", "ru": "университет", "uk": "університет"},
        "åker": {"en": "goes / travels", "ru": "едет", "uk": "їде"},
        "ett jobb": {"en": "job", "ru": "работа", "uk": "робота"},
        "varje": {"en": "every", "ru": "каждый", "uk": "кожен"},
        "en morgon": {"en": "morning", "ru": "утро", "uk": "ранок"},
        "tillbaka": {"en": "back", "ru": "назад", "uk": "назад"},
        "sitter": {"en": "sits", "ru": "сидит", "uk": "сидить"},
        "väntar": {"en": "waits", "ru": "ждёт", "uk": "чекає"},
        "honom": {"en": "him", "ru": "его", "uk": "його"},
        "kommer": {"en": "comes", "ru": "приходит", "uk": "приходить"},
        "aldrig": {"en": "never", "ru": "никогда", "uk": "ніколи"},
        "sjuk": {"en": "sick", "ru": "больной", "uk": "хворий"},
        "dör": {"en": "dies", "ru": "умирает", "uk": "помирає"},
        "dog": {"en": "died", "ru": "умер", "uk": "помер"},
        "tror": {"en": "believes", "ru": "верит", "uk": "вірить"},
        "en människa": {"en": "person", "ru": "человек", "uk": "людина"},
        "ger": {"en": "gives", "ru": "даёт", "uk": "дає"},
        "en vår": {"en": "spring", "ru": "весна", "uk": "весна"},
        "en sommar": {"en": "summer", "ru": "лето", "uk": "літо"},
        "en höst": {"en": "autumn", "ru": "осень", "uk": "осінь"},
        "en vinter": {"en": "winter", "ru": "зима", "uk": "зима"},
    },

    "Joshua studerar på distans": {
        "en distans": {"en": "distance", "ru": "дистанция", "uk": "дистанція"},
        "digital": {"en": "digital", "ru": "цифровой", "uk": "цифровий"},
        "en föreläsning": {"en": "lecture", "ru": "лекция", "uk": "лекція"},
        "en ordföljd": {"en": "word order", "ru": "порядок слов", "uk": "порядок слів"},
        "uppmärksam": {"en": "attentive", "ru": "внимательный", "uk": "уважний"},
        "antecknar": {"en": "takes notes", "ru": "делает записи", "uk": "робить записи"},
        "omvänd": {"en": "inverted", "ru": "обратный", "uk": "зворотний"},
        "koncentrerar sig": {"en": "concentrates", "ru": "концентрируется", "uk": "концентрується"},
        "inloggad": {"en": "logged in", "ru": "вошёл в систему", "uk": "увійшов у систему"},
        "en pandemi": {"en": "pandemic", "ru": "пандемия", "uk": "пандемія"},
        "pågår": {"en": "is ongoing", "ru": "продолжается", "uk": "триває"},
        "en undervisning": {"en": "teaching", "ru": "обучение", "uk": "навчання"},
        "en mening": {"en": "sentence", "ru": "предложение", "uk": "речення"},
        "knackar": {"en": "knocks", "ru": "стучит", "uk": "стукає"},
        "inneboende": {"en": "lodger", "ru": "квартирант", "uk": "квартирант"},
        "fokuserar": {"en": "focuses", "ru": "фокусируется", "uk": "фокусується"},
        "ett gruppsamtal": {"en": "group discussion", "ru": "групповой разговор", "uk": "групова розмова"},
        "kallar": {"en": "calls", "ru": "называет / зовёт", "uk": "називає"},
        "ett möte": {"en": "meeting", "ru": "встреча", "uk": "зустріч"},
        "förkyld": {"en": "having a cold", "ru": "простужен", "uk": "застуджений"},
        "ifred": {"en": "in peace", "ru": "в покое", "uk": "у спокої"},
        "bestämmer sig": {"en": "decides", "ru": "решает", "uk": "вирішує"},
        "en diskbänk": {"en": "kitchen sink", "ru": "кухонная раковина", "uk": "кухонна мийка"},
        "hemifrån": {"en": "from home", "ru": "из дома", "uk": "з дому"},
        "ett wifi": {"en": "wifi", "ru": "вайфай", "uk": "вайфай"},
        "strular": {"en": "malfunctions", "ru": "глючит", "uk": "глючить"},
        "missar": {"en": "misses", "ru": "пропускает", "uk": "пропускає"},
        "märker": {"en": "notices", "ru": "замечает", "uk": "помічає"},
        "rör på sig": {"en": "moves", "ru": "двигается", "uk": "рухається"},
        "sätter sig": {"en": "sits down", "ru": "садится", "uk": "сідає"},
    }

}